/**
 * Mock catalogue for Bosphorus Horology.
 * Replace `images` with your own product photography and `look` is used only
 * for the built-in watch illustration that appears while photos load (or if
 * a photo URL ever fails).
 */

export const categories = [
  "Automatic Chronograph",
  "Minimalist Steel",
  "Vintage Leather",
  "Gold-Plated",
  "Sport Diver",
];

export const movements = ["Automatic", "Manual Wind", "Swiss Quartz", "Skeleton Automatic"];

/* ---------- image pool (Unsplash watch photography, swap for your own) ---------- */
const POOL = [
  "1523170335258-f5ed11844a49",
  "1524592094714-0f0654e20314",
  "1547996160-81dfa63595aa",
  "1522312346375-d1a52e2b99b3",
  "1508685096489-7aacd43bd3b1",
  "1434056886845-dac89ffe9b56",
  "1542496658-e33a6d0d50f6",
  "1533139502658-0198f920d8e8",
  "1548171915-e79a380a2a4b",
  "1526045431048-f857369baa09",
  "1539874754764-5a96559165b0",
  "1587836374828-4dbafa94cf0e",
];
const img = (id) => `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=1400&q=80`;
const gallery = (i) => [0, 3, 5, 8].map((k) => img(POOL[(i + k) % POOL.length]));

/* ---------- palette shorthand ---------- */
const C = {
  steel: "#b8bcc6",
  gold: "#d2ac5e",
  rose: "#c98f6b",
  black: "#2a2c31",
  bronze: "#a9743f",
  gunmetal: "#5b6270",
};
const D = {
  midnight: "#0f1a33",
  iznik: "#1f5f8b",
  ivory: "#e9e0cb",
  cream: "#efe4c8",
  black: "#0d0d0f",
  green: "#1f3a2e",
  slate: "#3a4252",
  champagne: "#d8c79a",
  burgundy: "#4a1a26",
  silver: "#cfd3da",
  pearl: "#eee8e2",
  sage: "#7f9482",
};
const S = {
  tan: "#8b5a2b",
  brown: "#4a2c1a",
  black: "#141416",
  bracelet: "#9ea3ad",
  blue: "#1c2b4a",
  green: "#22382e",
  cognac: "#9b5b2e",
  rubber: "#1b1d22",
  mesh: "#aeb3bd",
};
const GOLD_ACC = "#e2c88a";
const INK_ACC = "#1a1a1a";

const movementInfo = {
  Automatic: { caliber: "Caliber BH-A21, 25 jewels", reserve: "46 hours", freq: "28,800 vph (4 Hz)" },
  "Manual Wind": { caliber: "Caliber BH-M11, 21 jewels", reserve: "72 hours", freq: "21,600 vph (3 Hz)" },
  "Swiss Quartz": { caliber: "Swiss quartz, thermo-compensated", reserve: "8-year battery life", freq: "32,768 Hz" },
  "Skeleton Automatic": { caliber: "Caliber BH-S30, 27 jewels", reserve: "60 hours", freq: "28,800 vph (4 Hz)" },
};

const categoryInfo = {
  "Automatic Chronograph": { water: "100 m / 10 ATM", crystal: "Sapphire, anti-reflective" },
  "Minimalist Steel": { water: "50 m / 5 ATM", crystal: "Sapphire, flat" },
  "Vintage Leather": { water: "30 m / 3 ATM", crystal: "Domed sapphire" },
  "Gold-Plated": { water: "50 m / 5 ATM", crystal: "Sapphire, anti-reflective" },
  "Sport Diver": { water: "300 m / 30 ATM", crystal: "Sapphire, double anti-reflective" },
};

function build(s, i) {
  const m = movementInfo[s.movement];
  const c = categoryInfo[s.category];
  return {
    id: s.id,
    title: s.title,
    tagline: s.tagline,
    category: s.category,
    movement: s.movement,
    price: s.price,
    rating: s.rating,
    reviews: s.reviews,
    description: s.description,
    stock: s.stock,
    stockCount: s.stockCount,
    images: gallery(i),
    look: s.look,
    featured: s.featured,
    isNew: s.isNew,
    order: i,
    specs: [
      { label: "Reference", value: `BH-${1001 + i}` },
      { label: "Case", value: `${s.size} mm diameter, ${s.thick} mm thick` },
      { label: "Case material", value: s.caseMat },
      { label: "Dial", value: s.dialName },
      { label: "Crystal", value: c.crystal },
      { label: "Movement", value: `${s.movement}, ${m.caliber}` },
      { label: "Power reserve", value: m.reserve },
      { label: "Frequency", value: m.freq },
      { label: "Water resistance", value: s.water ?? c.water },
      { label: "Strap", value: s.strapName },
      { label: "Lug width", value: `${s.size >= 41 ? 22 : s.size >= 37 ? 20 : 18} mm` },
    ],
  };
}

const seeds = [
  /* ------------------------- Automatic chronographs ------------------------- */
  {
    id: "galata-chronograph",
    title: "Galata Chronograph",
    tagline: "Midnight sunburst, steel bracelet",
    category: "Automatic Chronograph",
    movement: "Automatic",
    price: 4850,
    rating: 4.9,
    reviews: 212,
    stock: "in-stock",
    stockCount: 12,
    description:
      "A 42 mm automatic chronograph named for the tower above the Golden Horn. Its sunburst dial shifts from ink to cobalt as the light moves across it.",
    size: 42,
    thick: 13.4,
    caseMat: "316L stainless steel, brushed and polished",
    dialName: "Midnight blue sunburst with three registers",
    strapName: "Steel H-link bracelet with folding clasp",
    look: { case: C.steel, dial: D.midnight, strap: S.bracelet, accent: GOLD_ACC },
    featured: true,
  },
  {
    id: "karakoy-regatta",
    title: "Karaköy Regatta",
    tagline: "Iznik blue with a ten-minute countdown",
    category: "Automatic Chronograph",
    movement: "Automatic",
    price: 5200,
    rating: 4.8,
    reviews: 143,
    stock: "in-stock",
    stockCount: 8,
    description:
      "Built around a ten-minute regatta countdown, with a bright Iznik-blue dial and a contrast-orange chronograph hand. Made for the harbour races off Kalamış.",
    size: 43,
    thick: 14.1,
    caseMat: "316L stainless steel, sandblasted",
    dialName: "Iznik blue lacquer with regatta timer",
    strapName: "Blue sailcloth-texture rubber strap",
    look: { case: C.steel, dial: D.iznik, strap: S.blue, accent: "#f0a35e" },
  },
  {
    id: "topkapi-panda",
    title: "Topkapı Panda",
    tagline: "Ivory dial, black registers",
    category: "Automatic Chronograph",
    movement: "Automatic",
    price: 4650,
    rating: 4.7,
    reviews: 118,
    stock: "in-stock",
    stockCount: 9,
    description:
      "A reverse-panda take on the classic racing chronograph, with a warm ivory dial, black registers, and a tachymeter scale in fine black print.",
    size: 40,
    thick: 12.8,
    caseMat: "316L stainless steel, polished",
    dialName: "Ivory grain with black registers",
    strapName: "Black perforated calfskin",
    look: { case: C.steel, dial: D.ivory, strap: S.black, accent: INK_ACC },
    featured: true,
  },
  {
    id: "sariyer-racing",
    title: "Sarıyer Racing",
    tagline: "Black dial, bronze registers",
    category: "Automatic Chronograph",
    movement: "Automatic",
    price: 5600,
    rating: 4.8,
    reviews: 64,
    stock: "in-stock",
    stockCount: 6,
    description:
      "Black dial, bronze-tone registers and a matte bezel. The most dramatic chronograph in the collection, named for the fishing town where the Bosphorus meets the Black Sea.",
    size: 43,
    thick: 14.0,
    caseMat: "Black DLC-coated steel",
    dialName: "Matte black with bronze registers",
    strapName: "Tobacco nubuck leather",
    look: { case: C.black, dial: D.black, strap: S.cognac, accent: "#c88b4f" },
    isNew: true,
  },
  {
    id: "dolmabahce-flyback",
    title: "Dolmabahçe Flyback",
    tagline: "Two-tone steel and gold",
    category: "Automatic Chronograph",
    movement: "Automatic",
    price: 7400,
    rating: 4.9,
    reviews: 87,
    stock: "low-stock",
    stockCount: 2,
    description:
      "A two-tone flyback chronograph that restarts timing with a single press. The chamfers are polished to echo the gilded interiors of the palace it is named for.",
    size: 41,
    thick: 13.6,
    caseMat: "Steel with 18k gold-plated bezel and crown",
    dialName: "Champagne with applied gold indices",
    strapName: "Two-tone steel and gold bracelet",
    look: { case: C.gold, dial: D.champagne, strap: S.bracelet, accent: INK_ACC },
    featured: true,
  },
  {
    id: "rumeli-hisari",
    title: "Rumeli Hisarı",
    tagline: "Gunmetal, notched like fortress walls",
    category: "Automatic Chronograph",
    movement: "Automatic",
    price: 6150,
    rating: 4.6,
    reviews: 52,
    stock: "in-stock",
    stockCount: 5,
    description:
      "A gunmetal case and slate dial, with a crenellated bezel notched like the fortress walls it is named for. Heavy on the wrist and impossible to miss.",
    size: 44,
    thick: 14.8,
    caseMat: "Gunmetal PVD steel",
    dialName: "Slate with luminous Arabic numerals",
    strapName: "Grey woven textile with leather lining",
    look: { case: C.gunmetal, dial: D.slate, strap: S.rubber, accent: "#d8dde6" },
  },

  /* ---------------------------- Minimalist steel ---------------------------- */
  {
    id: "moda-slim",
    title: "Moda Slim",
    tagline: "8.2 mm, hand-wound",
    category: "Minimalist Steel",
    movement: "Manual Wind",
    price: 2450,
    rating: 4.8,
    reviews: 176,
    stock: "in-stock",
    stockCount: 14,
    description:
      "At 8.2 mm thick, the slimmest watch we make. Hand-wound, with a matte silver dial and a single line of blued hands.",
    size: 39,
    thick: 8.2,
    caseMat: "316L stainless steel, polished",
    dialName: "Matte silver with blued hands",
    strapName: "Grey suede",
    look: { case: C.steel, dial: D.silver, strap: "#5d6068", accent: "#2b4a86" },
    featured: true,
  },
  {
    id: "cihangir-three-hand",
    title: "Cihangir Three-Hand",
    tagline: "The everyday automatic",
    category: "Minimalist Steel",
    movement: "Automatic",
    price: 2980,
    rating: 4.7,
    reviews: 203,
    stock: "in-stock",
    stockCount: 18,
    description:
      "The everyday watch: steel case, satin dial, sapphire caseback. Named for the hillside quarter where Istanbul's writers drink their morning tea.",
    size: 40,
    thick: 10.4,
    caseMat: "316L stainless steel, brushed",
    dialName: "Satin charcoal with applied batons",
    strapName: "Steel bracelet with quick-release links",
    look: { case: C.steel, dial: D.slate, strap: S.bracelet, accent: "#e6e9ef" },
  },
  {
    id: "bebek-date",
    title: "Bebek Date",
    tagline: "Swiss quartz, pearl dial",
    category: "Minimalist Steel",
    movement: "Swiss Quartz",
    price: 1450,
    rating: 4.5,
    reviews: 158,
    stock: "in-stock",
    stockCount: 25,
    description:
      "Swiss quartz precision in a 38 mm case, with a date window at six and a fine-grained pearl dial. Sits easily under a cuff.",
    size: 38,
    thick: 9.1,
    caseMat: "316L stainless steel, polished",
    dialName: "Pearl with date at six",
    strapName: "Steel mesh bracelet",
    look: { case: C.steel, dial: D.pearl, strap: S.mesh, accent: INK_ACC },
  },
  {
    id: "balat-mesh",
    title: "Balat Mesh",
    tagline: "Sage sunburst on Milanese mesh",
    category: "Minimalist Steel",
    movement: "Automatic",
    price: 2690,
    rating: 4.6,
    reviews: 71,
    stock: "in-stock",
    stockCount: 10,
    description:
      "A sage-green sunburst dial on a Milanese mesh bracelet, inspired by the painted houses that climb the hill above the Golden Horn.",
    size: 39,
    thick: 10.0,
    caseMat: "316L stainless steel, brushed",
    dialName: "Sage green sunburst",
    strapName: "Milanese mesh bracelet, magnetic clasp",
    look: { case: C.steel, dial: D.sage, strap: S.mesh, accent: "#f1f3ee" },
  },
  {
    id: "pera-bluesteel",
    title: "Pera Bluesteel",
    tagline: "Heat-blued hands, graduated slate dial",
    category: "Minimalist Steel",
    movement: "Automatic",
    price: 3150,
    rating: 4.9,
    reviews: 96,
    stock: "in-stock",
    stockCount: 7,
    description:
      "Heat-blued steel hands over a dial that graduates from slate to midnight. Named for Pera, the old European quarter above Galata.",
    size: 40,
    thick: 10.8,
    caseMat: "316L stainless steel, polished and brushed",
    dialName: "Graduated slate blue",
    strapName: "Midnight blue alligator-grain leather",
    look: { case: C.steel, dial: "#26345a", strap: S.blue, accent: "#7aa0ff" },
  },
  {
    id: "kadikoy-field",
    title: "Kadıköy Field",
    tagline: "Hand-wound with high-contrast numerals",
    category: "Minimalist Steel",
    movement: "Manual Wind",
    price: 2250,
    rating: 4.6,
    reviews: 109,
    stock: "in-stock",
    stockCount: 11,
    description:
      "A hand-wound field watch with high-contrast numerals and an anti-magnetic movement shield. Sized for the ferry ride across to Asia.",
    size: 38,
    thick: 10.9,
    caseMat: "316L stainless steel, bead-blasted",
    dialName: "Matte black with cream numerals",
    strapName: "Olive canvas with leather lining",
    look: { case: C.steel, dial: D.black, strap: "#3b4230", accent: "#efe4c8" },
  },

  /* ----------------------------- Vintage leather ---------------------------- */
  {
    id: "kapalicarsi-1957",
    title: "Kapalıçarşı 1957",
    tagline: "The founding watch, revived",
    category: "Vintage Leather",
    movement: "Manual Wind",
    price: 3450,
    rating: 4.9,
    reviews: 189,
    stock: "in-stock",
    stockCount: 9,
    description:
      "Our founding watch, revived: domed crystal, cream dial with aged lume, and a tan calfskin strap. Hand-wound, as it began.",
    size: 36,
    thick: 10.6,
    caseMat: "316L steel with a warm satin finish",
    dialName: "Cream with aged-lume numerals",
    strapName: "Tan calfskin, hand-stitched",
    look: { case: "#c9c2b0", dial: D.cream, strap: S.tan, accent: "#5a3b1a" },
    featured: true,
  },
  {
    id: "sultanahmet-heritage",
    title: "Sultanahmet Heritage",
    tagline: "Roman numerals, railway track",
    category: "Vintage Leather",
    movement: "Manual Wind",
    price: 3850,
    rating: 4.8,
    reviews: 74,
    stock: "out-of-stock",
    stockCount: 0,
    description:
      "Roman numerals, a railway minute track and a small seconds sub-dial in a 36 mm case that sits close to the wrist.",
    size: 36,
    thick: 10.2,
    caseMat: "316L steel, polished",
    dialName: "Ivory enamel-effect with Roman numerals",
    strapName: "Dark brown calfskin",
    look: { case: C.steel, dial: D.ivory, strap: S.brown, accent: "#2a1a10" },
  },
  {
    id: "ortakoy-tonneau",
    title: "Ortaköy Tonneau",
    tagline: "Cushion case, visible rotor",
    category: "Vintage Leather",
    movement: "Automatic",
    price: 3600,
    rating: 4.7,
    reviews: 58,
    stock: "in-stock",
    stockCount: 6,
    description:
      "A tonneau case with a cushion profile and an ivory dial with a guilloché centre. The caseback window shows the rotor at work.",
    size: 37,
    thick: 10.9,
    caseMat: "Steel with rose-gold tone plating",
    dialName: "Ivory with guilloché centre",
    strapName: "Chestnut calfskin",
    look: { case: C.rose, dial: D.ivory, strap: "#6b3f22", accent: "#3a2416" },
  },
  {
    id: "fener-officer",
    title: "Fener Officer",
    tagline: "Fine dial ring, sub-seconds at six",
    category: "Vintage Leather",
    movement: "Manual Wind",
    price: 2890,
    rating: 4.6,
    reviews: 82,
    stock: "in-stock",
    stockCount: 8,
    description:
      "An officer's watch with a fine dial ring and a sub-seconds register at six, on a stitched chestnut strap.",
    size: 37,
    thick: 9.8,
    caseMat: "316L steel, satin finish",
    dialName: "Warm white with blued steel hands",
    strapName: "Chestnut calfskin, stitched",
    look: { case: C.steel, dial: "#f0ead8", strap: "#6b3f22", accent: "#2b4a86" },
  },
  {
    id: "eminonu-bullhead",
    title: "Eminönü Bullhead",
    tagline: "Pushers on top, crown at twelve",
    category: "Vintage Leather",
    movement: "Manual Wind",
    price: 4100,
    rating: 4.7,
    reviews: 41,
    stock: "low-stock",
    stockCount: 3,
    description:
      "A bullhead chronograph with pushers on top of the case and a crown at twelve. A distinctive shape, a hand-wound movement, and a cognac strap.",
    size: 38,
    thick: 12.2,
    caseMat: "316L steel, brushed",
    dialName: "Cream with brown registers",
    strapName: "Cognac calfskin",
    look: { case: C.bronze, dial: D.cream, strap: S.cognac, accent: "#4a2c1a" },
  },
  {
    id: "uskudar-pilot",
    title: "Üsküdar Pilot",
    tagline: "Forest green with an oversized crown",
    category: "Vintage Leather",
    movement: "Automatic",
    price: 3300,
    rating: 4.7,
    reviews: 93,
    stock: "in-stock",
    stockCount: 13,
    description:
      "A forest-green dial, large Arabic numerals and an oversized crown that is easy to turn with gloves on.",
    size: 40,
    thick: 11.6,
    caseMat: "316L steel, bead-blasted",
    dialName: "Forest green with cream numerals",
    strapName: "Aged brown leather",
    look: { case: C.steel, dial: D.green, strap: S.brown, accent: "#efe4c8" },
  },

  /* ------------------------------ Gold-plated ------------------------------- */
  {
    id: "yildiz-royal",
    title: "Yıldız Royal",
    tagline: "Champagne dial, applied batons",
    category: "Gold-Plated",
    movement: "Automatic",
    price: 5900,
    rating: 4.9,
    reviews: 131,
    stock: "in-stock",
    stockCount: 5,
    description:
      "Five microns of 18k gold plating over steel, a champagne dial and applied batons. The classic dress watch, in warm gold.",
    size: 40,
    thick: 10.8,
    caseMat: "Steel with 5-micron 18k gold plating",
    dialName: "Champagne sunburst with applied batons",
    strapName: "Black alligator-grain leather",
    look: { case: C.gold, dial: D.champagne, strap: S.black, accent: INK_ACC },
    featured: true,
  },
  {
    id: "ciragan-skeleton",
    title: "Çırağan Skeleton",
    tagline: "Tulip-cut bridges under sapphire",
    category: "Gold-Plated",
    movement: "Skeleton Automatic",
    price: 8900,
    rating: 5.0,
    reviews: 47,
    stock: "low-stock",
    stockCount: 2,
    description:
      "A fully skeletonised movement under sapphire, with bridges cut into a tulip pattern. Every part of the mechanism is on show.",
    size: 41,
    thick: 12.5,
    caseMat: "Steel with 5-micron 18k gold plating",
    dialName: "Open-worked, gold-plated bridges",
    strapName: "Dark brown alligator-grain leather",
    look: { case: C.gold, dial: "#2a2118", strap: S.brown, accent: GOLD_ACC },
    featured: true,
  },
  {
    id: "sarayburnu-moonphase",
    title: "Sarayburnu Moonphase",
    tagline: "A moon that crosses the midnight sky",
    category: "Gold-Plated",
    movement: "Automatic",
    price: 7200,
    rating: 4.8,
    reviews: 29,
    stock: "in-stock",
    stockCount: 4,
    description:
      "A hand-painted moon travels across a midnight-blue dial. Named for the headland where the Bosphorus meets the Sea of Marmara.",
    size: 40,
    thick: 11.9,
    caseMat: "Steel with 5-micron 18k gold plating",
    dialName: "Midnight blue with moonphase aperture",
    strapName: "Navy alligator-grain leather",
    look: { case: C.gold, dial: D.midnight, strap: S.blue, accent: GOLD_ACC },
    isNew: true,
  },
  {
    id: "emirgan-tulip",
    title: "Emirgan Tulip",
    tagline: "Mother-of-pearl, rose gold tone",
    category: "Gold-Plated",
    movement: "Swiss Quartz",
    price: 2300,
    rating: 4.7,
    reviews: 105,
    stock: "in-stock",
    stockCount: 16,
    description:
      "Rose-gold plating and a mother-of-pearl dial painted with a single tulip, in a 32 mm case. Named for the park that fills with tulips every spring.",
    size: 32,
    thick: 8.6,
    caseMat: "Steel with rose-gold plating",
    dialName: "Mother-of-pearl with painted tulip",
    strapName: "Blush pink calfskin",
    look: { case: C.rose, dial: D.pearl, strap: "#c9a79c", accent: "#8a4f3c" },
  },
  {
    id: "suleymaniye-dress",
    title: "Süleymaniye Dress",
    tagline: "Black dial, gold Roman numerals",
    category: "Gold-Plated",
    movement: "Manual Wind",
    price: 4700,
    rating: 4.8,
    reviews: 62,
    stock: "in-stock",
    stockCount: 7,
    description:
      "A black dial, gold Roman numerals and a thin bezel. An understated evening watch with a hand-wound movement.",
    size: 38,
    thick: 9.4,
    caseMat: "Steel with 5-micron 18k gold plating",
    dialName: "Black lacquer with gold Roman numerals",
    strapName: "Black calfskin",
    look: { case: C.gold, dial: D.black, strap: S.black, accent: GOLD_ACC },
  },

  /* ------------------------------- Sport diver ------------------------------ */
  {
    id: "kiz-kulesi-diver",
    title: "Kız Kulesi Diver 300",
    tagline: "300 m, Bosphorus-blue lume",
    category: "Sport Diver",
    movement: "Automatic",
    price: 3950,
    rating: 4.8,
    reviews: 167,
    stock: "in-stock",
    stockCount: 15,
    description:
      "A 300 m diver with a unidirectional bezel and a dial that glows Bosphorus-blue. Named for the Maiden's Tower, alone on its islet.",
    size: 42,
    thick: 13.0,
    caseMat: "316L stainless steel, brushed",
    dialName: "Deep blue with luminous indices",
    strapName: "Steel bracelet with diver's extension",
    look: { case: C.steel, dial: "#12305a", strap: S.bracelet, accent: "#9fd4ff" },
    featured: true,
  },
  {
    id: "marmara-deep",
    title: "Marmara Deep 600",
    tagline: "600 m with helium escape valve",
    category: "Sport Diver",
    movement: "Automatic",
    price: 5450,
    rating: 4.9,
    reviews: 38,
    stock: "out-of-stock",
    stockCount: 0,
    water: "600 m / 60 ATM",
    description:
      "600 m water resistance, a helium escape valve and a screw-down crown. Built for the deep sea and finished to be worn everywhere else.",
    size: 44,
    thick: 15.2,
    caseMat: "316L stainless steel, bead-blasted",
    dialName: "Matte black with large luminous indices",
    strapName: "Black rubber with steel buckle",
    look: { case: C.gunmetal, dial: D.black, strap: S.rubber, accent: "#c9f0d2" },
  },
  {
    id: "buyukada-gmt",
    title: "Büyükada GMT",
    tagline: "Two time zones, one bi-colour bezel",
    category: "Sport Diver",
    movement: "Automatic",
    price: 4300,
    rating: 4.7,
    reviews: 84,
    stock: "in-stock",
    stockCount: 10,
    water: "200 m / 20 ATM",
    description:
      "A 200 m GMT with a bi-colour bezel for anyone who lives across two time zones. The fourth hand tracks home while the others keep local time.",
    size: 41,
    thick: 13.2,
    caseMat: "316L stainless steel, brushed",
    dialName: "Graphite with contrast GMT hand",
    strapName: "Steel bracelet, five-link",
    look: { case: C.steel, dial: D.slate, strap: S.bracelet, accent: "#e5786d" },
  },
  {
    id: "bogazici-skeleton-diver",
    title: "Boğaziçi Skeleton Diver",
    tagline: "Open dial, 200 m",
    category: "Sport Diver",
    movement: "Skeleton Automatic",
    price: 6800,
    rating: 4.8,
    reviews: 22,
    stock: "low-stock",
    stockCount: 3,
    water: "200 m / 20 ATM",
    description:
      "A skeletonised dial that shows the movement at work, in a case rated to 200 m. Proof that a diver does not have to hide its mechanics.",
    size: 43,
    thick: 14.0,
    caseMat: "Black DLC-coated steel",
    dialName: "Open-worked with bronze bridges",
    strapName: "Black rubber with bronze-tone buckle",
    look: { case: C.black, dial: "#1c1a18", strap: S.rubber, accent: "#c88b4f" },
    isNew: true,
  },
  {
    id: "anadolu-hisari-quartz",
    title: "Anadolu Hisarı Quartz Diver",
    tagline: "The entry diver, 200 m",
    category: "Sport Diver",
    movement: "Swiss Quartz",
    price: 1850,
    rating: 4.5,
    reviews: 141,
    stock: "in-stock",
    stockCount: 30,
    water: "200 m / 20 ATM",
    description:
      "Swiss quartz reliability, a rotating dive bezel and 200 m water resistance. The best way to start a collection.",
    size: 41,
    thick: 11.7,
    caseMat: "316L stainless steel, brushed",
    dialName: "Matte black with luminous indices",
    strapName: "Black rubber",
    look: { case: C.steel, dial: D.black, strap: S.rubber, accent: "#e6e9ef" },
  },
];

export const products = seeds.map((s, i) => build(s, i));

const byId = new Map(products.map((p) => [p.id, p]));
export const getProduct = (id) => byId.get(id);

export const featuredProducts = products.filter((p) => p.featured);

export const priceBounds = {
  min: Math.floor(Math.min(...products.map((p) => p.price)) / 100) * 100,
  max: Math.ceil(Math.max(...products.map((p) => p.price)) / 100) * 100,
};

export function relatedProducts(p, n = 4) {
  const same = products.filter((x) => x.id !== p.id && x.category === p.category);
  const rest = products.filter((x) => x.id !== p.id && x.category !== p.category);
  return [...same, ...rest].slice(0, n);
}
